### ISSUE TITLE
Image links and folder doesn't match

### ISSUE THREAD

**Issue by cstby** [artiomn/markdown_articles_tool#17]
The script downloaded the images perfectly into an /images folder in the same directory as the files. However, the markdown links only reference the image by name and should be prepended with `/images/`. Maybe I just need to specify this when running the command, but I'm not sure from the instructions how to do that.

**Comment by artiomn** [comment]
You can use option `-n, --replace-image-names` to replace image names with a hash from the image content.

**Comment by alanalvarado** [comment]
Thank you for this great piece of work. However, I can confirm that the program is not prepending the image path into the link. I tried the -n option, but it also only replaces the name, not the path.

**Comment by artiomn** [comment]
Ok, I understand what you want and will implement it as soon as possible.

**Comment by artiomn** [comment]
Feature was added.

**Comment by artiomn** [comment]
https://github.com/artiomn/markdown_articles_tool/commit/cd7f4624535c14a24ef06e821fccaefd001b8c40
