### ISSUE TITLE
Link is deleted even though no image was found

### ISSUE THREAD

**Issue by Quentin50** [artiomn/markdown_articles_tool#18]
Hello

My users may introduce a mistake when writing markdown, tagging an important link as an image. As a result, the tool will try to download the html and then delete the link. Losing the link from the article is a problem. 

For example in a md file containing

`Important link to remember:  ![](https://www.google.com/)`

the link would be deleted when processing the article, resulting in the following

`Important link to remember:  ![](.html)`

A solution to this particular case would be to raise an exception when replacing the image link if the file name is empty. In `www_tools.py` after line 73 in function `get_filename_from_url`, add

`    if f_name == "":
        raise ValueError(f'F_name is empty {req.url}')`

However, the problem would persist for certain links. 

`Important link:  ![](https://github.com/artiomn/markdown_articles_tool)` 
would still be replaced by 
`Important link:  ![](markdown_articles_tool.html)`

In this case it would be necessary to check the MIME type of the downloaded content before replacing the link.

**Comment by artiomn** [comment]
Thank you for the informative description. Now work in progress. I'll merge this bugfix with the big change.

**Comment by artiomn** [comment]
Fixed.

**Comment by artiomn** [comment]
- https://github.com/artiomn/markdown_articles_tool/commit/3ce48ddd3087401ad3702ff48db107facaad58ef
- https://github.com/artiomn/markdown_articles_tool/commit/0d5b56d9c13fbcfb0f57fea43428373aa2d5c185

**Comment by Quentin50** [comment]
Thank you. It seems to work fine for what I have tested so far.
