### ISSUE TITLE
--replace-image-names Option Not Implemented

### ISSUE THREAD

**Issue by cnberg** [artiomn/markdown_articles_tool#24]
I tried using the --replace-image-names option as described in the README, but it seems like this feature is not implemented yet. When I use it, no image names are actually replaced. Could you please confirm if this feature is currently available or not? If it's not implemented yet, it would be a really useful addition to the tool.

Steps to Reproduce:

Run command markdown_articles_tool --replace-image-names ...
Observe that image names are not replaced.
Expected Outcome:
Image names should be replaced as per the documentation.

Actual Outcome:
No image names were replaced.

Thank you for looking into this issue.

**Comment by cnberg** [comment]
Upon inspecting the code in markdown_tool.py, I noticed that while --replace-image-names is added as an argument on line 98 using parser.add_argument, there is no subsequent implementation that actually uses this argument in the code (e.g., it's missing around line 54 where arguments are processed).

This leads to the --replace-image-names feature not working as expected. Could you please confirm if this is a bug or if the feature is yet to be implemented?

Many thanks.

**Comment by artiomn** [comment]
Yes, probably this is a bug, and I'll fix it, when I have a time.
