### ISSUE TITLE
Missing png file extension

### ISSUE THREAD

**Issue by trongnguyen29** [artiomn/markdown_articles_tool#4]
When download from unsplash, there is no extension appended.

**Comment by artiomn** [comment]
Please, give me an URL example and downloaded filename example.

**Comment by artiomn** [comment]
Now tool is correctly guess an image type and adds file extension for the URLs like this: `https://plus.unsplash.com/premium_photo-1669689974101-55f9aea22158?q=80&w=2576&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D`.

**Comment by artiomn** [comment]
I think, issue can be closed.
