### ISSUE TITLE
Option to specify output filename

### ISSUE THREAD

**Issue by varac** [artiomn/markdown_articles_tool#5]
Thanks for this nice tool !
Currently the output filename is non-deterministic which makes it hard to use in batch scripts.
Please provide a parameter like `--out FILENAME` or sth like this.

**Comment by artiomn** [comment]
Added (`--output-path`):
https://github.com/artiomn/markdown_articles_tool/commit/138499a126fe884ba96de606084d31ab9fb58bbf
https://github.com/artiomn/markdown_articles_tool/commit/dc7e143bafe1f258a4c2772fb9c7e83480f402ee

**Comment by varac** [comment]
Awesome, thanks !

**Comment by artiomn** [comment]
You're welcome.
