### ISSUE TITLE
Markdown articles on pypi

### ISSUE THREAD

**Issue by melvio** [artiomn/markdown_articles_tool#6]
Thanks @artiomn for the awesome project! Just what I was looking for.

Would it be possible to make this project available on [pypi](https://pypi.org/)?

**Comment by artiomn** [comment]
Thank you for the idea.
Merged: https://github.com/artiomn/markdown_articles_tool/commit/2a73f002f18071f14c6dc449d5f00eb9db2c68ea
[First, manually build package on PyPI](https://pypi.org/project/markdown-tool/).
