### ISSUE TITLE
Local image processing

### ISSUE THREAD

**Issue by mrkingmidas** [artiomn/markdown_articles_tool#7]
Hello!
Can you add processing "local" images ? Copying (relative and absolute paths) and replacing path in file
For example, files in folders:
```
1\Test.md
1\_d\1.png
_resources\2.png
```
Content of Test.md:
```md
![](https://pandoc.org/diagram.jpg)

![](_d/1.png)

![](../_resources/2.png)
```
and command:
```
markdown_tool.py Test.md -D -d out -p out -O Test2.md
```
Produces files:
```
out\diagram.jpg
```
and file `Test2.md`
```md
![](out/diagram.jpg)

![](_d/1.png)

![](../_resources/2.png)
```

Needed:
```
out\diagram.jpg
out\1.jpg
out\2.jpg
```
and file:
```md
![](out/diagram.jpg)

![](out/1.png)

![](out/2.png)
```

**Comment by mrkingmidas** [comment]
Hello!

I am implement processing local images:
```
parser.add_argument('-l', '--process-local-images', default=False, action='store_true',
                      help='Process local images')
```
https://www.dropbox.com/s/sgdpwzhnshstcto/ProcessLocalImagesReplaceNameSHA1.zip?dl=1

**Comment by artiomn** [comment]
Hello.

I think this is a useful feature.
However, it will be better if you would make a pull request via github.

**Comment by mrkingmidas** [comment]
> I think this is a useful feature. However, it will be better if you would make a pull request via github.
Unfortunately, I have not yet learned how to use git and upload changes :-(

**Comment by artiomn** [comment]
You can:

- Use Github web interface to edit files.
- Use crossplatform GUI tools, integrated with github, i.e.:
  * [SmartGit](https://www.syntevo.com/smartgit/).
  * [Atlassian SourceTree](https://confluence.atlassian.com/get-started-with-sourcetree/connect-your-bitbucket-or-github-account-847359096.html).
  * [Github Desktop](https://desktop.github.com/).
  * Any of [these](https://git-scm.com/downloads/guis).
- Console helpers, like oh-my-zsh git plugin or pure git console:
  * `git clone <https://github.com/user/repository>`
  * `git add <changed files>` or `git rm <files to remove>`.
  * `git commit -m <commit message>`
  * `git push`
  * That's all the commands, to get started.

You can read the basics in the [official "ProGit" book](https://git-scm.com/book/en/v2), translated to the most common languages.

**Comment by artiomn** [comment]
Merged:

- https://github.com/artiomn/markdown_articles_tool/commit/d85d76e269046ca14fc3eb301d563b9636602972
- https://github.com/artiomn/markdown_articles_tool/commit/4bf55437d21c3d10f266245124abc72d915c5480

**Comment by artiomn** [comment]
Please, use Git next time.
