### ISSUE TITLE
Option to replace image file name with hash

### ISSUE THREAD

**Issue by mrkingmidas** [artiomn/markdown_articles_tool#8]
Hello!
Can you add option to replace image file name with hash ?
Needed for using in "media" big folder for markdown notes: "deduplicate" while processing many notes and for an unique file names

**Comment by mrkingmidas** [comment]
Hello!

I am implement replacing names with SHA1 of content:
```
parser.add_argument('-n', '--replace-image-names', default=False, action='store_true',
                        help='Replace image names, using content hash')
```
https://www.dropbox.com/s/sgdpwzhnshstcto/ProcessLocalImagesReplaceNameSHA1.zip?dl=1

**Comment by artiomn** [comment]
Could you make pull request, please?
Dropbox is not very convenient solution.
It's better to look at the diff and process the review.

**Comment by artiomn** [comment]
Merged:

- https://github.com/artiomn/markdown_articles_tool/commit/d85d76e269046ca14fc3eb301d563b9636602972
- https://github.com/artiomn/markdown_articles_tool/commit/4bf55437d21c3d10f266245124abc72d915c5480

**Comment by artiomn** [comment]
Option was merged with `-D`, as a `names_hashing`.
